name: Build OpenWrt 23.05 Packages

on:
  workflow_dispatch:

jobs:
  sync:
    name: Sync Upstream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: pkgs

      - name: Update Feeds
        run: |
          bash update-feeds.sh
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Git Push
        continue-on-error: true
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          [ -d .git ] && git init
          git add .
          git commit -sm "Sync - ${{env.latest_release}}"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:pkgs

  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    needs: sync
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: pkgs

      - name: Build Packages
        uses: sbwml/openwrt-gh-action-sdk@go1.23
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_lite
          PACKAGES: luci-app-alist alist
          INDEX: 1
          KEY_BUILD: ${{ secrets.OPENWRT_PRIVATE_KEY }}
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Upload packages_lite
        run: |
          mkdir -p /tmp/openwrt_pkgs/${{ matrix.arch }}/
          mv bin/packages/${{ matrix.arch }}/packages_lite/* /tmp/openwrt_pkgs/${{ matrix.arch }}
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Git push
        continue-on-error: true
        run: |
          rm -rf openwrt_pkgs/23.05/${{ matrix.arch }}
          mkdir -p openwrt_pkgs/23.05/${{ matrix.arch }}
          mv /tmp/openwrt_pkgs/${{ matrix.arch }} ./openwrt_pkgs/23.05
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          [ -d .git ] && git init
          git add openwrt_pkgs/23.05/${{ matrix.arch }}
          git commit -sm "Update ${{ matrix.arch }} packages_lite - ${{env.latest_release}}"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:gh-pages --force

  deploy:
    name: Pages Build and Deployment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages
      - name: Pages Deployment
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pages/builds
