name: Build OpenWrt 23.05 Packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Packages
        run: |
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV
          bash update-feeds.sh ${{ matrix.arch }}

      - name: Build Packages
        uses: pmkol/openwrt-gh-action-sdk@pkgs
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          PACKAGES: luci-app-frpc
          INDEX: 1
          KEY_BUILD: ${{ secrets.OPENWRT_PRIVATE_KEY }}
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Upload packages_ci
        run: |
          mkdir -p /tmp/openwrt_pkgs/${{ matrix.arch }}/
          mv bin/packages/${{ matrix.arch }}/packages/* /tmp/openwrt_pkgs/${{ matrix.arch }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Git push
        continue-on-error: true
        run: |
          rm -rf openwrt_pkgs/23.05/${{ matrix.arch }}
          mkdir -p openwrt_pkgs/23.05/${{ matrix.arch }}
          mv /tmp/openwrt_pkgs/${{ matrix.arch }} ./openwrt_pkgs/23.05
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          [ -d .git ] && git init
          git add openwrt_pkgs/23.05/${{ matrix.arch }}
          git commit -sm "Update ${{ matrix.arch }} packages_ci - ${{env.latest_release}}"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:gh-pages --force
