name: Trigger GitHub Pages Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: gh-pages

    - name: Feed
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: packages
        force_orphan: true
        commit_message: Update Feed
